//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPSLSGAMEver5.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPSLSGAMEver5.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an item:
        ///Paper - P
        ///Scissor - S
        ///Rock - R
        ///Lizard - L
        ///Spock -V.
        /// </summary>
        internal static string gameAvailableItems {
            get {
                return ResourceManager.GetString("gameAvailableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both identities are equal.
        /// </summary>
        internal static string gameItemsEqualMessage {
            get {
                return ResourceManager.GetString("gameItemsEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Game rules: 
        ///Scissors cuts Paper
        ///Paper covers Rock
        ///Rock crushes Lizard
        ///Lizard poisons Spock
        ///Spock smashes Scissors
        ///Scissors decapitates Lizard
        ///Lizard eats Paper
        ///Paper disproves Spock
        ///Spock vaporizes Rock
        ///Rock crushes Scissors.
        /// </summary>
        internal static string gameRulesMessage {
            get {
                return ResourceManager.GetString("gameRulesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameResult.txt.
        /// </summary>
        internal static string gameSavedDataFileName {
            get {
                return ResourceManager.GetString("gameSavedDataFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPSLS GAME.
        /// </summary>
        internal static string gameTitle {
            get {
                return ResourceManager.GetString("gameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the RPSLS Game
        ///Rock, Paper, Scissor, Lizard, Spock
        ///If you need to read the game rules hit the H key
        ///Hit the E key to start the game or hit the Q key to quit the game.
        /// </summary>
        internal static string gameWelcomeMessage {
            get {
                return ResourceManager.GetString("gameWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The machine choosed:.
        /// </summary>
        internal static string machineChoosedOtionMessage {
            get {
                return ResourceManager.GetString("machineChoosedOtionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine point:.
        /// </summary>
        internal static string machinePointMessage {
            get {
                return ResourceManager.GetString("machinePointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your name:.
        /// </summary>
        internal static string playerAddNameMessage {
            get {
                return ResourceManager.GetString("playerAddNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are choosed:.
        /// </summary>
        internal static string playerChoosedOptionMessage {
            get {
                return ResourceManager.GetString("playerChoosedOptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to save the result hit the C key
        ///If you want to start a new game without save the result hit the E key
        ///If you want to exit the game without save hit the Q key.
        /// </summary>
        internal static string playerGameFinalizeNavigationMessage {
            get {
                return ResourceManager.GetString("playerGameFinalizeNavigationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to go back to the main screen hit the B key
        ///If you want to quit the game hit the Q key.
        /// </summary>
        internal static string playerGameRulesNavigationMessage {
            get {
                return ResourceManager.GetString("playerGameRulesNavigationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please hit a valid key:.
        /// </summary>
        internal static string playerHitValidKeyMessage {
            get {
                return ResourceManager.GetString("playerHitValidKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are LOSE! :(
        ///The winner is:.
        /// </summary>
        internal static string playerLoseMessage {
            get {
                return ResourceManager.GetString("playerLoseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name:.
        /// </summary>
        internal static string playerNameMessage {
            get {
                return ResourceManager.GetString("playerNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player point:.
        /// </summary>
        internal static string playerPointMessage {
            get {
                return ResourceManager.GetString("playerPointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are WIN! :)
        ///The winner is:.
        /// </summary>
        internal static string playerWinMessage {
            get {
                return ResourceManager.GetString("playerWinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for player input:.
        /// </summary>
        internal static string WaitForInputMessage {
            get {
                return ResourceManager.GetString("WaitForInputMessage", resourceCulture);
            }
        }
    }
}
